baseurl: ""
url: "https://najoe-repositories.github.io"
permalink: pretty
title: "NAJOE"
description: "Jo (Najoe) — Site Reliability Engineer, DevOps, Security Research, Fullstack & WordPress. Najoe Solutions."

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - .github
